#! /usr/bin/env python
# encoding: utf-8
import sys

def run_tests(ctx):
    sys.path.append(ctx.top_dir)
    import waf_tools

    waf_tools.run_tests(ctx)


def configure(cfg):
    cfg.env.append_value('LIB',['fix8', 'PocoNet', 'PocoFoundation'])

def build(bld):

    sys.path.append(bld.top_dir)
    import waf_tools

    IncludePaths =  waf_tools.get_module_include_dirs(bld,'common')
    IncludePaths =  IncludePaths  + waf_tools.get_module_include_dirs(bld,'matching-engine')
    IncludePaths.append('include')

    #Build the static library
    # find all .cpp files ( exclude unit tests )
    bin_sources_files =  bld.path.ant_glob('**/*.cpp',excl=['**/test_*.cpp'])
    bld.program( source = bin_sources_files, target="bin/trading-gateway", use="matching-engine common LEVELDB", includes=IncludePaths )
    if bld.env.with_unittest:
        waf_tools.build_tests(bld, "common matching-engine GTEST", IncludePaths)