# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 358)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Pricelabel = QtWidgets.QLabel(self.centralwidget)
        self.Pricelabel.setObjectName("Pricelabel")
        self.horizontalLayout_3.addWidget(self.Pricelabel)
        self.PricelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PricelineEdit.setObjectName("PricelineEdit")
        self.horizontalLayout_3.addWidget(self.PricelineEdit)
        self.Qtylabel = QtWidgets.QLabel(self.centralwidget)
        self.Qtylabel.setObjectName("Qtylabel")
        self.horizontalLayout_3.addWidget(self.Qtylabel)
        self.QtylineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.QtylineEdit.setObjectName("QtylineEdit")
        self.horizontalLayout_3.addWidget(self.QtylineEdit)
        self.Sidelabel = QtWidgets.QLabel(self.centralwidget)
        self.Sidelabel.setObjectName("Sidelabel")
        self.horizontalLayout_3.addWidget(self.Sidelabel)
        self.SidecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SidecomboBox.setObjectName("SidecomboBox")
        self.SidecomboBox.addItem("")
        self.SidecomboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.SidecomboBox)
        self.InstrumentIDlabel = QtWidgets.QLabel(self.centralwidget)
        self.InstrumentIDlabel.setObjectName("InstrumentIDlabel")
        self.horizontalLayout_3.addWidget(self.InstrumentIDlabel)
        self.InstrumentIDlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.InstrumentIDlineEdit.setObjectName("InstrumentIDlineEdit")
        self.horizontalLayout_3.addWidget(self.InstrumentIDlineEdit)
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setObjectName("SendButton")
        self.horizontalLayout_3.addWidget(self.SendButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.Pricelabel.setText(_translate("MainWindow", "Price"))
        self.PricelineEdit.setText(_translate("MainWindow", "12"))
        self.Qtylabel.setText(_translate("MainWindow", "Quantity"))
        self.QtylineEdit.setText(_translate("MainWindow", "34"))
        self.Sidelabel.setText(_translate("MainWindow", "Side"))
        self.SidecomboBox.setItemText(0, _translate("MainWindow", "BUY"))
        self.SidecomboBox.setItemText(1, _translate("MainWindow", "SELL"))
        self.InstrumentIDlabel.setText(_translate("MainWindow", "Instrument ID"))
        self.InstrumentIDlineEdit.setText(_translate("MainWindow", "1"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

