#! /usr/bin/env python3
# encoding: utf-8
import sys
import os
from subprocess import call


def run_tests(ctx):
    pass


def generate_protobuf_api(bld):
    saved_dir = os.getcwd()
    os.chdir("%s/config/" % bld.path.relpath())
    call(["protoc", "protocol.proto", "--python_out=protocol"])
    os.chdir(saved_dir)


def configure(cfg):
    cfg.find_program('pyuic5', var='PYUIC5')


def build(bld):
    sys.path.append(bld.top_dir)
    import waf_tools

    # bld(rule='cp ${SRC} ${TGT}', source='config/config.ini', target='bin/config.ini')
